const API='/api';const $=s=>document.querySelector(s);let mobile='';
async function request(path,options={}){const r=await fetch(`${API}${path}`,{credentials:'include',headers:{'content-type':'application/json',...(options.headers||{})},...options});const data=await r.json().catch(()=>({ok:false,code:'INVALID_RESPONSE'}));if(r.status===401)showLogin();if(!r.ok)throw Object.assign(new Error(data.code||'REQUEST_FAILED'),{data,status:r.status});return data}
function text(v){return v==null?'—':String(v)}function esc(v){return text(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function table(headers,rows){return `<table><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${headers.length}">داده‌ای وجود ندارد.</td></tr>`}</tbody></table>`}
function showLogin(){ $('#loginPanel').hidden=false;$('#dashboard').hidden=true }
function showDashboard(){ $('#loginPanel').hidden=true;$('#dashboard').hidden=false }
async function loadDashboard(){const d=await request('/admin/dashboard');showDashboard();$('#healthChip').className=`chip ${d.ok?'ok':'bad'}`;$('#healthChip').textContent=d.ok?'سامانه پایدار':'نیازمند بررسی';$('#metrics').innerHTML=[['نوبت امروز',d.metrics.appointmentsToday],['پیام در صف',d.metrics.queuePending],['مکالمه باز',d.metrics.openConversations],['Backup تأییدشده',d.metrics.verifiedBackups]].map(([l,v])=>`<article class="metric"><span>${esc(l)}</span><strong>${esc(v)}</strong></article>`).join('');$('#services').innerHTML=Object.entries(d.services).map(([k,v])=>`<article class="serviceCard"><header><b>${esc(k)}</b><i class="dot ${v.ok?'ok':v.configured?'warn':'bad'}"></i></header><p>${esc(v.message|| (v.ok?'فعال':v.configured?'تنظیم‌شده':'تنظیم‌نشده'))}</p></article>`).join('');renderSchedule(d.schedule);renderQueue(d.queue);renderConversations(d.conversations);renderCampaigns(d.campaigns);renderUsers(d.users);renderBackups(d.backups)}
function renderSchedule(items=[]){$('#scheduleList').innerHTML=table(['روز/تاریخ','شروع','پایان','ظرفیت','وضعیت'],items.map(x=>`<tr><td>${esc(x.jalali_date||x.weekday)}</td><td>${esc(x.starts_at)}</td><td>${esc(x.ends_at)}</td><td>${esc(x.capacity)}</td><td>${x.is_closed?'بسته':'باز'}</td></tr>`))}
function renderQueue(items=[]){$('#queueList').innerHTML=table(['کانال','گیرنده','الگو','وضعیت','تلاش','عملیات'],items.map(x=>`<tr><td>${esc(x.channel)}</td><td>${esc(x.recipient)}</td><td>${esc(x.template_code)}</td><td>${esc(x.status)}</td><td>${esc(x.attempts)}</td><td><button data-retry="${esc(x.id)}">ارسال مجدد</button></td></tr>`))}
function renderConversations(items=[]){$('#conversationList').innerHTML=table(['کانال','بیمار','وضعیت','آخرین پیام','عملیات'],items.map(x=>`<tr><td>${esc(x.channel)}</td><td>${esc(x.patient_name)}</td><td>${esc(x.status)}</td><td>${esc(x.last_message)}</td><td><button data-handoff="${esc(x.id)}">انتقال به منشی</button></td></tr>`))}
function renderCampaigns(items=[]){$('#campaignList').innerHTML=table(['نام','کد','تخفیف','شروع','پایان','وضعیت'],items.map(x=>`<tr><td>${esc(x.title)}</td><td>${esc(x.code)}</td><td>${esc(x.discount_value)}</td><td>${esc(x.starts_at)}</td><td>${esc(x.ends_at)}</td><td>${x.enabled?'فعال':'غیرفعال'}</td></tr>`))}
function renderUsers(items=[]){$('#userList').innerHTML=table(['نام','موبایل','وضعیت','نقش‌ها'],items.map(x=>`<tr><td>${esc(x.display_name)}</td><td>${esc(x.mobile)}</td><td>${esc(x.status)}</td><td>${esc((x.roles||[]).join('، '))}</td></tr>`))}
function renderBackups(items=[]){$('#backupList').innerHTML=table(['تاریخ','ارائه‌دهنده','وضعیت','رمزگذاری','Checksum'],items.map(x=>`<tr><td>${esc(x.created_at)}</td><td>${esc(x.provider)}</td><td>${esc(x.status)}</td><td>${x.encrypted?'بله':'خیر'}</td><td>${esc((x.checksum_sha256||'').slice(0,16))}…</td></tr>`))}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();mobile=$('#mobile').value.trim();try{await request('/auth/request-otp',{method:'POST',body:JSON.stringify({mobile,purpose:'admin-login'})});$('#verifyForm').hidden=false;$('#loginStatus').textContent='کد تأیید ارسال شد.'}catch(err){$('#loginStatus').textContent=err.data?.message||'ارسال کد انجام نشد.'}})
$('#verifyForm').addEventListener('submit',async e=>{e.preventDefault();try{await request('/auth/verify-otp',{method:'POST',body:JSON.stringify({mobile,code:$('#otp').value.trim(),purpose:'admin-login'})});await loadDashboard()}catch(err){$('#loginStatus').textContent=err.data?.message||'کد معتبر نیست.'}})
$('#refreshBtn').addEventListener('click',()=>loadDashboard().catch(console.error));$('#logoutBtn').addEventListener('click',async()=>{await request('/auth/logout',{method:'POST'}).catch(()=>{});showLogin()});
document.addEventListener('click',async e=>{const tab=e.target.closest('[data-tab]');if(tab){document.querySelectorAll('[data-tab],.tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');$(`#${tab.dataset.tab}`).classList.add('active')}const retry=e.target.closest('[data-retry]');if(retry){await request('/admin/queue',{method:'PATCH',body:JSON.stringify({id:retry.dataset.retry,action:'retry'})});await loadDashboard()}const handoff=e.target.closest('[data-handoff]');if(handoff){await request('/admin/conversations',{method:'PATCH',body:JSON.stringify({id:handoff.dataset.handoff,status:'handoff'})});await loadDashboard()}if(e.target.closest('[data-action="retryFailed"]')){await request('/admin/queue',{method:'PATCH',body:JSON.stringify({action:'retry-all-failed'})});await loadDashboard()}if(e.target.closest('[data-action="verifyBackup"]')){await request('/admin/backups',{method:'POST',body:JSON.stringify({action:'verify-latest'})});await loadDashboard()}})
loadDashboard().catch(()=>showLogin());